import React from 'react';

export default function Disclaimer() {
  return (
    <div style={{ background: '#fff', minHeight: '100vh' }}>
      <div className="legal-page">
        <h1>Important information about Pickwise recommendations</h1>
        <p className="last-updated">Last updated: 28 June 2026</p>

        <h2>AI-generated content</h2>
        <p>Pickwise recommendations are generated by artificial intelligence (Anthropic's Claude model) using real-time web search and publicly available information. While we strive for accuracy, AI can and does make mistakes. Results may occasionally be outdated, incomplete, or inaccurate. Always verify important information independently before making a purchase, booking, or other decision.</p>

        <h2>Not professional advice</h2>
        <p>Nothing on Pickwise constitutes professional advice of any kind:</p>
        <ul>
          <li><strong>Health results are NOT medical advice.</strong> Always consult a qualified, registered healthcare professional before making any health or medical decision, changing medication, or acting on health information.</li>
          <li><strong>Legal results are NOT legal advice.</strong> Always consult a qualified solicitor or legal professional regulated in your jurisdiction. Do not act on legal information from Pickwise without professional verification.</li>
          <li><strong>Financial results are NOT financial advice.</strong> Always consult an FCA-regulated financial adviser (UK) or equivalent in your jurisdiction before making any investment, pension, mortgage, or financial decision.</li>
        </ul>

        <h2>No endorsement</h2>
        <p>Listing a business, product, or service on Pickwise does not constitute an endorsement by us. We do not have commercial relationships with listed businesses unless explicitly stated as sponsored. AI-generated rankings reflect publicly available reputation signals, not our personal endorsement.</p>

        <h2>Trademarks</h2>
        <p>All brand names, logos, and trademarks appearing in Pickwise recommendations are the property of their respective owners. Their appearance on Pickwise does not imply any affiliation with or endorsement by those trademark holders.</p>

        <h2>Accuracy of local information</h2>
        <p>Business hours, stock levels, prices, and availability change frequently. Always check directly with the business before visiting or purchasing. Pickwise cannot guarantee that local information is current at the time you view it.</p>

        <h2>Limitation of liability</h2>
        <p>Pickwise accepts no liability for any loss, damage, injury, or expense arising from reliance on AI-generated recommendations. Use this service at your own discretion and judgment. By using Pickwise, you acknowledge that recommendations are for informational purposes only.</p>

        <h2>Report inaccuracies</h2>
        <p>Found an error? Use the "⚑ Report" button on any result card, or email: <a href="mailto:accuracy@pickwise.com">accuracy@pickwise.com</a>. We take accuracy seriously and review all reports.</p>
      </div>
    </div>
  );
}
